build: off
platform: x64
version: '{build}'
clone_folder: c:/rattletrap
environment:
  GITHUB_TOKEN:
    secure: 'L/78Qw3wSosowhhilcm/u+wHOM97yiHdXgz8pbwRD3PQVtVSB1lZQ/BDaIm8RpsA'
  PATH: c:/bin;%PATH%
  STACK_ROOT: c:/stack

install:
  - powershell -File tools/install-stack.ps1
test_script:
  - stack --jobs 1 setup > nul
  - stack build --jobs 1 --only-dependencies --test rattletrap
  - stack build --ghc-options -O2 --jobs 1 --pedantic --test rattletrap
  - stack --jobs 1 sdist .
on_success:
  - stack --jobs 1 build rattletrap-tools
  - stack attach-binary
